/**
 * i18n.js — Data loaders, country/language helpers, and language switching
 */

import ENV_CONFIG  from './env-config.js';

const SITE_CONFIG = window.CONFIG || {};
const STORAGE_KEY = SITE_CONFIG.storageKeys?.lang;
const BASE        = () => SITE_CONFIG.appearance?.base_path;

// Get supported languages from manifest (loaded by site-boot.js)
// Falls back to config.defaultLanguage if manifest unavailable
function getSupportedLanguages() {
    // Prefer manifest (generated by build script)
    if (window.__supportedLanguages && window.__supportedLanguages.length > 0) {
        return window.__supportedLanguages.map(code => ({ 
            code: code, 
            hreflang: code 
        }));
    }
    
    // Fallback to config.js languages if available
    if (SITE_CONFIG.languages && SITE_CONFIG.languages.length > 0) {
        return SITE_CONFIG.languages;
    }
    
    // Ultimate fallback: just use default language from config
    const defaultLang = SITE_CONFIG.defaultLanguage || 'en';
    return [{ code: defaultLang, hreflang: defaultLang }];
}

// ── DATA LOADERS ─────────────────────────────────────────────────────────────

const _langCache = {};

export async function loadLanguage(langCode) {
    // Return in-memory cache if already loaded for this code
    if (_langCache[langCode]) return _langCache[langCode];

    const url = BASE() + SITE_CONFIG.paths.lang_dir + langCode + '/common.json';
    try {
        const res = await fetch(url);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        _langCache[langCode] = data;
        return data;
    } catch {
        // Fallback to default language (from config or manifest)
        const defaultLang = SITE_CONFIG.defaultLanguage || 'en';
        if (langCode !== defaultLang) return loadLanguage(defaultLang);
        return {};
    }
}

// ── COUNTRY HELPERS ───────────────────────────────────────────────────────

export function getLanguageByCountry(data, code) {
    const country = (data || []).find(c => c.code === code?.toUpperCase());
    if (!country || !country.active) return null;
    return country.language || null;
}

// ── LANGUAGE DATA HELPERS ─────────────────────────────────────────────────────

export function getCountryName(langData, code, _targetLang) {
    return langData?.country_names?.[code?.toUpperCase()] || code;
}

export function getSlug(langData, pageKey) {
    return langData?.url_slugs?.[pageKey] || pageKey;
}

/** Reverse lookup: URL segment → canonical page key, given current lang bundle */
export function canonicalSlug(langData, urlSegment) {
    const slugs = langData?.url_slugs || {};
    const entry = Object.entries(slugs).find(([, v]) => v === urlSegment);
    return entry ? entry[0] : null;
}

export function cartUrl(basePath, langCode, langData) {
    const slug = langData?.url_slugs?.cart || 'cart';
    return `${basePath}${langCode}/${slug}/`;
}

export function getProfileLabel(langData, profileId) {
    return langData?.profiles?.[profileId] || profileId;
}

// ── STORAGE HELPERS ───────────────────────────────────────────────────────────

export function getStoredLanguage() {
    try { return localStorage.getItem(STORAGE_KEY); } catch { return null; }
}

export function setStoredLanguage(lang) {
    try { localStorage.setItem(STORAGE_KEY, lang); } catch {}
}

// ── HREFLANG ─────────────────────────────────────────────────────────────────

export function injectHreflangTags(slug, langData) {
    const languages = getSupportedLanguages();
    const root      = SITE_CONFIG.appearance.root_url;
    document.querySelectorAll('link[rel="alternate"][hreflang]').forEach(el => el.remove());
    languages.forEach(({ code, hreflang }) => {
        const link    = document.createElement('link');
        link.rel      = 'alternate';
        link.hreflang = hreflang;
        link.href     = slug
            ? `${root}/${code}/${getSlug(langData, slug)}/`
            : `${root}/`;
        document.head.appendChild(link);
    });
    const xDef    = document.createElement('link');
    xDef.rel      = 'alternate';
    xDef.hreflang = 'x-default';
    xDef.href = slug ? `${root}/${languages[0].code}/${getSlug(langData, slug)}/` : `${root}/`;
    document.head.appendChild(xDef);
}

// ── LANGUAGE DETECTION ────────────────────────────────────────────────────────

function detectLang() {
    const languages = getSupportedLanguages();
    const supported = new Set(languages.map(l => l.code));

    const pageLang = window.__PAGE_LANG__;
    if (pageLang && supported.has(pageLang)) {
        setStoredLanguage(pageLang);
        return pageLang;
    }

    const saved = getStoredLanguage();
    if (saved && supported.has(saved)) return saved;

    const match = (navigator.languages || [navigator.language])
        .map(l => l.split('-')[0].toLowerCase())
        .find(l => supported.has(l));
    if (match) { setStoredLanguage(match); return match; }

    // Ultimate fallback: use default language from config
    const defaultLang = SITE_CONFIG.defaultLanguage || 'en';
    return defaultLang;
}

// ── SET LANG ──────────────────────────────────────────────────────────────────

window.setLang = async (code) => {
    setStoredLanguage(code);
    window.LANG = code;
    document.documentElement.setAttribute('lang', code);

    window.T = await loadLanguage(code);
    window.__CART_URL__ = cartUrl(BASE(), code, window.T);

    if (typeof window.renderNav    === 'function') window.renderNav();
    if (typeof window.renderFooter === 'function') window.renderFooter();

    if (typeof window.Shop !== 'undefined' && typeof window.Shop.switchLanguage === 'function') {
        try {
            await window.Shop.switchLanguage(code);
        } catch (e) {
            if (ENV_CONFIG.DEBUG) console.warn('[i18n] Shop.switchLanguage failed:', e);
        }
    }

    const slug = window.CURRENT_SLUG || '';
    if (slug) {
        const urlSlug = getSlug(window.T, slug);
        window.history.replaceState({ slug, lang: code }, '', `${BASE()}${code}/${urlSlug}/`);
        window.viewPage(slug, null, true);
    } else {
        // Update URL to reflect new language on home
        window.history.replaceState({ slug: '', lang: code }, '', `${BASE()}${code}/`);
        window.loadHome();
    }

    const langSelect = document.getElementById('langSelect');
    if (langSelect) langSelect.value = code;
};

// ── INIT ──────────────────────────────────────────────────────────────────────

export async function initI18n() {
    const lang  = detectLang();
    window.LANG = lang;
    document.documentElement.setAttribute('lang', lang);
    window.T    = await loadLanguage(lang);
    window.__CART_URL__ = cartUrl(BASE(), lang, window.T);
    injectHreflangTags('', window.T);
}


